/* FreeFem++ version information for MacOS 9 configuration */
/* File generated by configure.ac */

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "FreeFem++ 3.11"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "freefem++"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.11"

/* Version number of package */
#define VERSION "3.11"

/* FreeFem++ build date */
#define VersionFreeFemDate "Wed Dec 29 04:39:55 EET 2010"

/* FreeFem++ version as a float */
#define VersionFreeFempp (3.11)
