/* FreeFem++ version information for MacOS 9 configuration */
/* File generated by configure.ac */

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "FreeFem++ 3.10"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "freefem++"

/* Define to the version of this package. */
#define PACKAGE_VERSION "3.10"

/* Version number of package */
#define VERSION "3.10"

/* FreeFem++ build date */
#define VersionFreeFemDate "Tue Dec 28 13:26:43 EET 2010"

/* FreeFem++ version as a float */
#define VersionFreeFempp (3.10)
