/* FreeFem++ version information for MacOS 9 configuration */
/* File generated by configure.ac */

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "FreeFem++ 2.7"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "freefem++"

/* Define to the version of this package. */
#define PACKAGE_VERSION "2.7"

/* Version number of package */
#define VERSION "2.7"

/* FreeFem++ build date */
#define VersionFreeFemDate "Mon Apr 24 07:40:17 CEST 2006"

/* FreeFem++ version as a float */
#define VersionFreeFempp (2.7)
