.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH BAMG 1 "March 29, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
bamg \- mesh generator, converter and viewer
.SH SYNOPSIS
.B bamg,
.br
.B cvmsh2,
.br
.B drawbdmesh
.br
.SH DESCRIPTION
This manual page documents briefly the
.B bamg,
.B cvmsh2,
.B drawbdmesh
commands.
.br
.B bamg
is a mesh generator, 
.B cvmsh2 
is a mesh converter,
and 
.B drawbdmesh
is a mesh file viewer.
.br
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has detailed documentation in the manual.
.br
The extensive manual of FreeFem++ is written in LaTeX and it is available in
Postscript format in /usr/share/doc/freefem++/.
.SH AUTHOR
This manual page was written by Christophe Prud'homme <prudhomm@debian.org>,
for the Debian project (but may be used by others).
