.TH BAMG 1 "March 29, 2004"

.SH NAME
bamg \- mesh generator, converter and viewer

.SH SYNOPSIS
.B bamg
.br
.B cvmsh2
.br
.B drawbdmesh

.SH DESCRIPTION
This manual page documents briefly the
.B bamg,
.B cvmsh2,
.B drawbdmesh
commands.
.PP
.B bamg
is a mesh generator, 
.B cvmsh2 
is a mesh converter,
and 
.B drawbdmesh
is a mesh file viewer.
.PP
This manual page was written for the Debian distribution
because the original program does not have a manual page.

.SH SEE ALSO
The extensive manual of FreeFem++ is written in LaTeX and it is available in
Postscript and PDF format in /usr/share/doc/freefem++/.

.SH AUTHOR
This manual page was written by Christophe Prud'homme <\&prudhomm@debian.org\&>,
for the Debian project (but may be used by others).
