.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH FREEFEM++ 1 "March 29, 2004"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ff-get-dep \- tool to retreive dependence for compilation with FreeFem++ library
.SH SYNOPSIS
.B ff-get-dep
[\fIOPTIONS\fR] \fIFILE\fR
.SH DESCRIPTION
.PP
Reteive dependence needed to compile FILE with freefem+ library
.PP
Mandatory arguments to long options are mandatory for short options too.
.TP
\fB\-l*\fR
.TP
\fB\-dlib\fR
.TP
\fB\-dcpp\fR
.TP
\fB\-ff\fR
.PP
This manual page was written for the Debian distribution
because the original program does not have a manual page.
Instead, it has detailed documentation in the manual; see below.
.SH SEE ALSO
The extensive manual of FreeFem++ is written in LaTeX and it is available in
Postscript format in /usr/share/doc/freefem++/ on your hard disc.
.SH AUTHOR
This manual page was written by Christophe Trophime <christophe.trophime@grenoble.cnrs.fr>,
for the Debian project (but may be used by others).
