Document: freefem++
Title: Debian freefem++ Manual
Author: <insert document author here>
Abstract: This manual describes what freefem++ is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/freefem++/freefem++.sgml.gz

Format: postscript
Files: /usr/share/doc/freefem++/freefem++.ps.gz

Format: text
Files: /usr/share/doc/freefem++/freefem++.text.gz

Format: HTML
Index: /usr/share/doc/freefem++/html/index.html
Files: /usr/share/doc/freefem++/html/*.html
