.TH "FreeFem++-nw" "1" "January 2011"
.SH "NAME"
FreeFem++-nw \- Execute a FreeFem++ script file
.SH "SYNOPSIS" 
.PP 
FreeFem++-nw < scriptfile > 
.PP
.SH "DESCRIPTION" 
.PP 
FreeFem++-nw executes scriptfiles written in the FreeFem++, C++ like, language. The name of the scriptfile should have an .edp ending. No window is opened with this command, i.e any output is directed to the console. This command is identical to FreeFem++. 

.PP 
.SH "SEE ALSO" 
.PP 
FreeFem++, FreeFem++-mpi, FreeFem++-x11, FreeFem++-glx.
