examples++/*.edp          /usr/share/doc/freefem++/examples/
examples++-chapt3/*.edp   /usr/share/doc/freefem++/examples/
examples++-load/*.edp     /usr/share/doc/freefem++/examples/load
examples++-load/*.cpp     /usr/share/doc/freefem++/examples/load
examples++-other/*.edp    /usr/share/doc/freefem++/examples/other
examples++-bug/*.edp      /usr/share/doc/freefem++/examples/bug
examples++-eigen/*.edp    /usr/share/doc/freefem++/examples/eigen
examples++-mpi/*.edp      /usr/share/doc/freefem++/examples/mpi
examples++-tutorial/*.edp /usr/share/doc/freefem++/examples/tutorial


src/fflib/*.h*       /usr/include/freefem++
src/femlib/*.h*      /usr/include/freefem++
src/Graphics/*.h*    /usr/include/freefem++
*.h                  /usr/include/freefem++
examples++-load/*.so /usr/lib/freefem++
